### ISSUE TITLE
compile on erl 23.1.1 and gcc 10.2.1

### ISSUE THREAD

**Issue by MessageMap** [davisp/jiffy#205]
Versions:
`
>erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
23.1.1
>gcc --version
gcc (SUSE Linux) 10.2.1 20201028 [revision a78cd759754c92cecbf235ac9b447dcdff6c6e2f]
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

Error:
`
===> Verifying dependencies...
===> Compiling jiffy
Compiling c_src/decoder.c
In file included from c_src/decoder.c:10:
/usr/lib64/erlang/erts-11.1.1/include/erl_nif.h:1:1: error: expected identifier or â<U+0080><U+0098>(â<U+0080><U+0099> before â<U+0080><U+0098>!â<U+0080><U+0099> token
    1 | !<arch>
      | ^
/usr/lib64/erlang/erts-11.1.1/include/erl_nif.h:2:59: error: stray â<U+0080><U+0098>`â<U+0080><U+0099> in program
    2 | /               0           0     0     0       102       `
      |                                                           ^
/usr/lib64/erlang/erts-11.1.1/include/erl_nif.h:3:1: error: null character(s) ignored [-Werror]
    3 |    ^E  ^A^B  ^A^B  ^A^B  ^A^B  ^A^Bemtp_error_string emtp_get_info emtp_state_new emtp_state_destroy emtp_parse  //                                              28        `
      | ^
/usr/lib64/erlang/erts-11.1.1/include/erl_nif.h:3:4: error: stray â<U+0080><U+0098>\5â<U+0080><U+0099> in program
    3 |    ^E  ^A^B  ^A^B  ^A^B  ^A^B  ^A^Bemtp_error_string emtp_get_info emtp_state_new emtp_state_destroy emtp_parse  //                                              28        `

`

**Comment by davisp** [comment]
I'm gonna assume there was something wrong with either the Erlang install or a locale setting to get weird UTF-8 issues in erl_nif.h.
