### PR TITLE
Use rebar3 to build

### LINKED ISSUE #197: jiffy 1.0.4 fails to compile with Erlang/OTP 23.0-rc3
Compiling jiffy with Erlang/OTP 23.0-rc3 fails with the following error message:

```
$ make
./rebar compile
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{rebar_utils,get_cwd,[],[]},
                                 {rebar_config,new,0,[]},
                                 {rebar,init_config,1,[]},
                                 {rebar,run,1,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,758}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_em,1,[]}]}}
=ERROR REPORT==== 22-Apr-2020::13:39:22.741797 ===
beam/beam_load.c(1624): Error loading module rebar_utils:
  please re-compile this module with an 23 compiler (old-style fun with indices: 3/6)


=ERROR REPORT==== 22-Apr-2020::13:39:22.741840 ===
Loading of /home/magnus/src/jiffy-upstream/rebar/rebar/ebin/rebar_utils.beam failed: badfile

=ERROR REPORT==== 22-Apr-2020::13:39:22.761395 ===
beam/beam_load.c(1624): Error loading module rebar_utils:
  please re-compile this module with an 23 compiler (old-style fun with indices: 3/6)


=ERROR REPORT==== 22-Apr-2020::13:39:22.761467 ===
Loading of /home/magnus/src/jiffy-upstream/rebar/rebar/ebin/rebar_utils.beam failed: badfile

escript: exception error: undefined function rebar_utils:delayed_halt/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 127
```

This happens because release 23 dropped support for loading beam files compiled with a compiler older than R15 (see [here](https://github.com/erlang/otp/blob/OTP-23.0-rc3/erts/emulator/beam/beam_load.c#L1604-L1625)), and the beam files inside the `rebar` binary were compiled with R14.

### PR DESCRIPTION
**Pull request by aboroska**
Fixes #197 

This PR a POC how the build issue with Erlang 23 could be fixed.

Incompatible with very old Erlang versions, but those projects are less likely to upgrade jiffy anyway. 17.5 might work.

Let's see if travis has a recent enough `rebar3` version or we need to upgrade that.

### CODE REVIEW

**Comment by svh-pad** [comment]
I have a project that has jiffy as dependency and ran into #197 . Tried to fix it by using your branch instead, i.e. change my rebar.config to contain
```
{jiffy, {git, "https://github.com/aboroska/jiffy", {branch, "rebar3"}}},
```
The compilation now succeeds (`rebar3 as prod release`) but `rebar3 shell` stops working, giving only the following output and no repl:
```
===> Verifying dependencies...
===> Compiling jiffy
===> Linking /home/sam/paddy/_build/default/lib/jiffy/priv/jiffy.so
```
I'm not sure I 100% understand how the fix works so I'm not sure if this is something that's expected.

**Comment by aboroska** [comment]
@svh-pad Note that on some Erlang/rebar3 combinations you have to hit `Enter` or perhaps any key to get a shell prompt. Also make sure your rebar3 is up-to-date. `3.13.2` definitely works.

If that doesn't help try running rebar3 in debug mode to analyse the problem:

    rm -rf _build
    DEBUG=1 rebar3 shell

**Comment by michalwski** [comment]
Hi, thanks for the PR and attempt to make jiffy compiling under Erlang/OTP. Any chances this PR gets merged? The extra value is that the project will be adapted to the current build tools used by the Erlang community.

File: rebar.config [hunk 1]
```diff
@@ -36,5 +38,8 @@
     verbose
 ]}.
 
-{pre_hooks, [{"", compile, "escript enc compile"}]}.
-{post_hooks, [{"", clean, "escript enc clean"}]}.
+{provider_hooks,
+ [{pre, [
+    {compile, {pc, compile}},
+    {clean, {pc, clean}}
+  ]}]}.
```
Comment (jbernardo95) [inline rebar.config:45]: Don't know much about rebar and the pc plugin but shouldn't we keep the pre and post hooks?

```suggestion
{provider_hooks, [{pre, [{compile, {pc, compile}}]}
                  {post, [{compile, {pc, clean}}]}]}
```

Comment (kvelicka) [reply rebar.config:45]: Wow, well spotted!

Comment (aboroska) [reply rebar.config:45]: Great find, thank you @jbernardo95 !

Comment (aboroska) [reply rebar.config:45]: Wait! No. @jbernardo95  So your suggestion kinda works but not how it was before and not ideal either.

There are 2 hooks here: `compile` and `clean` and both are intended to run before the respective rebar3 commands. In theory the clean could be a post hook, but irrelevant.

So the intention is that `{pc, clean}` runs when someone issues `rebar3 clean`.

What your suggestion does is cleaning up immedately after `rebar3 compile`. Basically it will force `pc` to relink `jiffy.so` every time during compile, even though the artifact already exists.

Comment (jbernardo95) [reply rebar.config:45]: As I said, I don't know how rebar works and what these configs mean exactly I just asked the question based on the diff x)

What you said makes sense to me and seems to [be on par with the documentation](https://github.com/blt/port_compiler#use-with-existing-dependency) 👍

**Comment by darrenklein** [comment]
This resolved the issue for me, would love to see it get accepted. Thanks so much for your hard work!

**Comment by sgerrand** [comment]
☑️ Also worked for me. I'd love to see it get merged. 🤲

**Comment by kvelicka** [comment]
@davisp mentioning for visibility :crossed_fingers:

**Comment by featalion** [comment]
It compiles for me, but I got the next output when I try to run `rebar3` commands (e.g. `shell`, `eunit`):
```
failed with return code 1 and the following output:
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by KennethL** [comment]
the erl_interface lib  is removed in OTP 23 (was present in OTP 22).
I don't understand why erl_interface is needed at all when building Jiffy
which is implemented with NIFs.

/Kenneth

**Comment by featalion** [comment]
@KennethL hm, probably it is somewhere in my project and not related to Jiffy itself. I will investigate. Tack för tipset!

**Comment by featalion** [comment]
It seems that `erl_interface` linking flags come from the Port Compiler (`pc`) plugin for `rebar3`. I tried to get rid of those flags, but other modules in my project start to break... I don't have time to investigate further right now.

**Comment by NelsonVides** [comment]
@davisp is there any news about this? Any plans to make jiffy OTP23 compatible?

**Comment by davisp** [comment]
Apologies everyone. Been distracted by work and other craziness lately. I'll try and get to this by the end of the week.

**Comment by davisp** [comment]
There's a new 1.0.5 version on hex.pm if anyone wants to give that a whirl. I finally managed to get all the various Erlang versions installed locally to make this work happen. Apologies to everyone for the delay on supporting 23.0.

**Comment by darrenklein** [comment]
@davisp No way, thank you so much for all of your hard work!

**Comment by michalwski** [comment]
Thanks a lot @davisp !
